# Generated by Django 5.1.15 on 2026-04-29 01:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="资产名称"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(unpack_ipv4=True, verbose_name="IP地址"),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("server", "服务器"),
                            ("workstation", "终端"),
                            ("network", "网络设备"),
                            ("app", "应用系统"),
                        ],
                        default="server",
                        max_length=20,
                        verbose_name="资产类型",
                    ),
                ),
                (
                    "owner",
                    models.CharField(blank=True, max_length=50, verbose_name="负责人"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={"verbose_name": "资产", "verbose_name_plural": "资产",},
        ),
        migrations.CreateModel(
            name="HistoricalAsset",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="资产名称"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(unpack_ipv4=True, verbose_name="IP地址"),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("server", "服务器"),
                            ("workstation", "终端"),
                            ("network", "网络设备"),
                            ("app", "应用系统"),
                        ],
                        default="server",
                        max_length=20,
                        verbose_name="资产类型",
                    ),
                ),
                (
                    "owner",
                    models.CharField(blank=True, max_length=50, verbose_name="负责人"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="更新时间"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 资产",
                "verbose_name_plural": "historical 资产",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSecurityAlert",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="告警标题")),
                (
                    "level",
                    models.CharField(
                        choices=[("info", "信息"), ("warning", "警告"), ("danger", "高危")],
                        default="warning",
                        max_length=10,
                        verbose_name="告警等级",
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=100, verbose_name="告警来源"),
                ),
                ("detail", models.TextField(blank=True, verbose_name="告警详情")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="告警时间"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="data.asset",
                        verbose_name="关联资产",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 安全告警",
                "verbose_name_plural": "historical 安全告警",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVulnerability",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="漏洞标题")),
                (
                    "cve_id",
                    models.CharField(blank=True, max_length=30, verbose_name="CVE编号"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("low", "低危"),
                            ("medium", "中危"),
                            ("high", "高危"),
                            ("critical", "严重"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "待处理"),
                            ("processing", "处理中"),
                            ("closed", "已修复"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="漏洞描述")),
                (
                    "discovered_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="发现时间"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="data.asset",
                        verbose_name="关联资产",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 漏洞",
                "verbose_name_plural": "historical 漏洞",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SecurityAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="告警标题")),
                (
                    "level",
                    models.CharField(
                        choices=[("info", "信息"), ("warning", "警告"), ("danger", "高危")],
                        default="warning",
                        max_length=10,
                        verbose_name="告警等级",
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=100, verbose_name="告警来源"),
                ),
                ("detail", models.TextField(blank=True, verbose_name="告警详情")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="告警时间"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="data.asset",
                        verbose_name="关联资产",
                    ),
                ),
            ],
            options={"verbose_name": "安全告警", "verbose_name_plural": "安全告警",},
        ),
        migrations.CreateModel(
            name="Vulnerability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="漏洞标题")),
                (
                    "cve_id",
                    models.CharField(blank=True, max_length=30, verbose_name="CVE编号"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("low", "低危"),
                            ("medium", "中危"),
                            ("high", "高危"),
                            ("critical", "严重"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "待处理"),
                            ("processing", "处理中"),
                            ("closed", "已修复"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="漏洞描述")),
                (
                    "discovered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发现时间"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerabilities",
                        to="data.asset",
                        verbose_name="关联资产",
                    ),
                ),
            ],
            options={"verbose_name": "漏洞", "verbose_name_plural": "漏洞",},
        ),
    ]
