"""
Django settings for secSys project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "dev-only-insecure-key-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    "unfold",       # 
    "unfold.contrib.filters",       # 高级筛选
    "unfold.contrib.forms",         # 增强表单样式
    "unfold.contrib.inlines",       # 内联编辑
    "unfold.contrib.import_export", # 导入导出
    "unfold.contrib.guardian",      # 权限控制
    "unfold.contrib.simple_history", # 操作历史

    "import_export",
    "guardian",
    "simple_history",

    "data",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # simple_history 记录当前请求用户
    "simple_history.middleware.HistoryRequestMiddleware",

]

ROOT_URLCONF = "secSys.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],   # 模板路径
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "secSys.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]  # 没有 static 目录可先注释

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# guardian 必备
AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "guardian.backends.ObjectPermissionBackend",
)
ANONYMOUS_USER_ID = -1

# 安全基础（开发先保守，生产再严格）
X_FRAME_OPTIONS = "DENY"
SECURE_CONTENT_TYPE_NOSNIFF = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True




# unfold 可选配置（先放最小）
# settings.py
from django.urls import reverse_lazy


LOGIN_REDIRECT_URL = "/admin/security-dashboard/" # 登录后重定向到安全态势总览

UNFOLD = {
    "SITE_TITLE": "网络安全管理平台",
    "SITE_HEADER": "网络安全管理平台",
    "SITE_SYMBOL": "security",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "安全态势",
                "icon": "monitoring",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "总览看板",
                        "icon": "dashboard",
                        "link": reverse_lazy("security_dashboard"),
                    },
                ],
            },
            {
                "title": "数据库",
                "icon": "storage",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "资产",
                        "icon": "dns",
                        "link": reverse_lazy("admin:data_asset_changelist"),
                    },
                    {
                        "title": "漏洞",
                        "icon": "bug_report",
                        "link": reverse_lazy("admin:data_vulnerability_changelist"),
                    },
                    {
                        "title": "安全告警",
                        "icon": "warning",
                        "link": reverse_lazy("admin:data_securityalert_changelist"),
                    },
                ],
            },
            {
                "title": "认证和授权",
                "icon": "admin_panel_settings",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "用户",
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "组",
                        "icon": "groups",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}


